theme: jekyll-theme-cayman
title: Hello, Homepage!
description: If you've found your way here, double check that you're at the right place. If so, welcome! If not, skedaddle!
This is a new webpage for showcasing my future projects. Thanks for stopping by!
